# Simulación del Modelo Atmosférico Terrestre (ISA)

Este código de programación permite obtener los valores de Presión (P) y Temperatura (T) a un valor determinado de altura (h). 

Referencias:

[https://es.linkfang.org/wiki/Atmósfera_Estándar_Internacional]

In [64]:
#Importar librerías
import numpy as np
import pylab as plt
from pylab import show,plot,subplot,xlim,ylim,title,legend,xlabel,ylabel,figure

In [65]:
#Variables
#Definicion de variables base (1atm-950m-23°C) para el calculo de T(h) y P(h)
T0 = 296        #Temperatura Base [°K]
P0 = 101325     #Presión Base [Pa]
H0 = 1000       #Altura inicial [m]
Gt = float(-6.5/1000)  #Gradiente Termico Base [°K/m]
R = 287;        #Constante individual del aire [m^2/s^2*°K^2]

h=np.arange(1000,52000,1000).reshape(51,1)
g=len(h)
p = np.zeros((1,g))   #Vector de Presiones [Pa]
t = np.zeros((1,g))   #Vector de Temperaturas[°K]
C=0                   #Variable Contador
g1=np.arange(0,g,1)

A continuación se muestra el barrido para la obtención de P y T a partir de del vector h.

In [66]:
for i in g1:
    #Troposfera - Tropopausa
    if h[i]<=11000: #h<11000
        t[0,i]= T0 + Gt*(h[i]-H0)          #T[°K]
        p[0,i]= P0*(t[0,i]/T0)**(-9.8/(Gt*R)) #P[Pa]
        C = C+1
        
    #Actualizacion de los datos base
    if h[C-1]==11000:
        T0 = t[0,C-1]
        P0 = p[0,C-1]
        Gt = 0
        H0 = 11000

    #Tropopausa - Estratosfera  
    if(h[i]>11000 and h[i]<=20000): #h>11000 && h<=20000
        t[0,i]= T0                                #T[°K]
        p[0,i]= P0*np.exp((-9.8/(R*T0))*(h[i]-H0)) #P[Pa]
        C = C+1

    #Actualizacion de los datos base
    if(h[C-1]==20000):
        T0 = t[0,C-1]
        P0 = p[0,C-1]
        Gt = 1/1000
        H0 = 20000

    #Estratosfera - Estratosfera
    if(h[i]>20000 and h[i]<=32000): #h>20000 && h<=32000
        t[0,i]= T0+Gt*(h[i]-H0)            #T[°K]
        p[0,i]= P0*(t[0,i]/T0)**(-9.8/(Gt*R)) #P[Pa]
        C = C+1

    #Actualizacion de los datos base
    if(h[C-1]==32000):
        T0 = t[0,C-1]
        P0 = p[0,C-1]
        Gt = 2.8/1000
        H0 = 32000 

    #Estratosfera - Estratopausa
    if(h[i]>32000 and h[i]<=47000): #h>32000 && h<=47000
        t[0,i]= T0+Gt*(h[i]-H0)            #T[°K]
        p[0,i]= P0*(t[0,i]/T0)**(-9.8/(Gt*R)) #P[Pa]
        C = C+1

    #Actualizacion de los datos base
    if(h[C-1]==47000):
        T0 = t[0,C-1]
        P0 = p[0,C-1]
        Gt = 0
        H0 = 47000
 
    #Estratopausa - Mesosfera  
    if(h[i]>47000 and h[i]<=51000): #h>47000 && h<=51000
        t[0,i]= T0                                #T[°K]
        p[0,i]= P0*np.exp((-9.8/(R*T0))*(h[i]-H0)) #P[Pa]
        C = C+1

In [67]:
#Conversion de Unidades

for i in g1:
    p[0,i]=p[0,i]*0.009869*0.001; #P[Pa -> atm]

In [86]:
h_P_T=np.arange(153, dtype=float).reshape(51,3)
h_P_T[:,0]=np.transpose(h)
h_P_T[:,1]=p
h_P_T[:,2]=t
h_P_T=np.round(h_P_T,4)
print(h_P_T)

[[1.000e+03 1.000e+00 2.960e+02]
 [2.000e+03 8.899e-01 2.895e+02]
 [3.000e+03 7.898e-01 2.830e+02]
 [4.000e+03 6.991e-01 2.765e+02]
 [5.000e+03 6.169e-01 2.700e+02]
 [6.000e+03 5.428e-01 2.635e+02]
 [7.000e+03 4.761e-01 2.570e+02]
 [8.000e+03 4.161e-01 2.505e+02]
 [9.000e+03 3.624e-01 2.440e+02]
 [1.000e+04 3.145e-01 2.375e+02]
 [1.100e+04 2.718e-01 2.310e+02]
 [1.200e+04 2.345e-01 2.310e+02]
 [1.300e+04 2.023e-01 2.310e+02]
 [1.400e+04 1.745e-01 2.310e+02]
 [1.500e+04 1.505e-01 2.310e+02]
 [1.600e+04 1.298e-01 2.310e+02]
 [1.700e+04 1.120e-01 2.310e+02]
 [1.800e+04 9.660e-02 2.310e+02]
 [1.900e+04 8.330e-02 2.310e+02]
 [2.000e+04 7.190e-02 2.310e+02]
 [2.100e+04 6.200e-02 2.320e+02]
 [2.200e+04 5.350e-02 2.330e+02]
 [2.300e+04 4.630e-02 2.340e+02]
 [2.400e+04 4.000e-02 2.350e+02]
 [2.500e+04 3.460e-02 2.360e+02]
 [2.600e+04 2.990e-02 2.370e+02]
 [2.700e+04 2.590e-02 2.380e+02]
 [2.800e+04 2.250e-02 2.390e+02]
 [2.900e+04 1.950e-02 2.400e+02]
 [3.000e+04 1.690e-02 2.410e+02]
 [3.100e+0

In [87]:
#Guardar los valores de P y T en un .txt
np.savetxt('h_P_T.txt', h_P_T, fmt='%f')

In [88]:
leer=np.loadtxt('h_P_T.txt')
print(leer)

[[1.000e+03 1.000e+00 2.960e+02]
 [2.000e+03 8.899e-01 2.895e+02]
 [3.000e+03 7.898e-01 2.830e+02]
 [4.000e+03 6.991e-01 2.765e+02]
 [5.000e+03 6.169e-01 2.700e+02]
 [6.000e+03 5.428e-01 2.635e+02]
 [7.000e+03 4.761e-01 2.570e+02]
 [8.000e+03 4.161e-01 2.505e+02]
 [9.000e+03 3.624e-01 2.440e+02]
 [1.000e+04 3.145e-01 2.375e+02]
 [1.100e+04 2.718e-01 2.310e+02]
 [1.200e+04 2.345e-01 2.310e+02]
 [1.300e+04 2.023e-01 2.310e+02]
 [1.400e+04 1.745e-01 2.310e+02]
 [1.500e+04 1.505e-01 2.310e+02]
 [1.600e+04 1.298e-01 2.310e+02]
 [1.700e+04 1.120e-01 2.310e+02]
 [1.800e+04 9.660e-02 2.310e+02]
 [1.900e+04 8.330e-02 2.310e+02]
 [2.000e+04 7.190e-02 2.310e+02]
 [2.100e+04 6.200e-02 2.320e+02]
 [2.200e+04 5.350e-02 2.330e+02]
 [2.300e+04 4.630e-02 2.340e+02]
 [2.400e+04 4.000e-02 2.350e+02]
 [2.500e+04 3.460e-02 2.360e+02]
 [2.600e+04 2.990e-02 2.370e+02]
 [2.700e+04 2.590e-02 2.380e+02]
 [2.800e+04 2.250e-02 2.390e+02]
 [2.900e+04 1.950e-02 2.400e+02]
 [3.000e+04 1.690e-02 2.410e+02]
 [3.100e+0